/**:
  ros__parameters:
    common:
      lid_topic: /livox/lidar
      imu_topic: /livox/imu
      time_sync_en: false
    preprocess:
      lidar_type: 1
      scan_line: 6
      blind: 4.0
      time_scale: 0.001
    mapping:
      acc_cov: 0.1
      gyr_cov: 0.1
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      fov_degree: 90
      det_range: 450.0
      extrinsic_est_en: false
      extrinsic_T:
      - 0.04165
      - 0.02326
      - -0.0284
      extrinsic_R:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
    publish:
      path_publish_en: false
      scan_publish_en: true
      scan_effect_pub_en: true
      dense_publish_en: false
      scan_bodyframe_pub_en: true
    path_save_en: true
    pcd_save:
      pcd_save_en: true
      interval: -1
    feature_extract_enable: false
    point_filter_num: 3
    max_iteration: 3
    filter_size_surf: 0.5
    filter_size_map: 0.5
    cube_side_length: 1000.0
    ivox_grid_resolution: 0.5
    ivox_nearby_type: 18
    esti_plane_threshold: 0.1
